#!/bin/bash

EXPLAIN_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
VENV_DIR=$1
mkdir -p $VENV_DIR
cd $VENV_DIR
rm -Rf venv
virtualenv -p python3.5 venv
source venv/bin/activate
cd ${EXPLAIN_DIR}/../../pyelftools
pip install .
cd ${EXPLAIN_DIR}
python setup.py sdist
pip install --no-binary :all: dist/explain-1.0.tar.gz
rm -Rf dist
deactivate
